### ISSUE TITLE
不应该使用 pdf 文件吧

### ISSUE THREAD

**Issue by yanyiwu** [ProChain/WhitePaper#1]
pdf不利于在github上更新维护，也不利于传播，为什么不用markdown？

**Comment by croath** [comment]
目前 PDF 中有一些比较复杂的排版格式，比方说图片和公式，如果转换成 markdown，可能需要图片托管和 LATEX 介入，非系统化统筹的零散图片资源不是特别好管理，特别是有资源频繁更新的情况。

目前白皮书主要是通过官网传播，这里主要是备份留档，以及给工程师朋友一个可以方便参考的地方。

感谢你的问题，如果你有改进建议或者更好的办法，欢迎提给我们：）

**Comment by croath** [comment]
Will be reopened if there were any updates here.
